# Generated by Django 3.1.2 on 2020-10-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_entrada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
